name: Flutter Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Pull Flutter Image
        run: docker pull ghcr.io/cirruslabs/flutter:3.32.7

      - name: Install Dependencies
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/cirruslabs/flutter:3.41.6 \
            flutter pub get

      - name: Build APK
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ghcr.io/cirruslabs/flutter:3.41.6 \
            flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
